#!/usr/bin/env bash
# transfers a file from a client to a server with scp

# Validate the arguments ($#) if it is less than 3
if [ "$#" -lt 3 ]; then
	# we peint a usage message to the stdOut
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

# for areguments that are less than 4 = 3
elif [ "$#" -lt 4 ]; then
	# transfer a file
	# $1: the first argument. $2, $3 consecutively.
	# $1: the path to the file to be transfered
	# $2: the IP address of the server
	# $3: The username on the server
	# '$3@$2':~/ : the destination for scp transfer (username@IP address): home directory
        scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
# if aregument is more than 4
else
        scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
