#!/usr/bin/env bash
# This installs the nginx server and configures it on the remote server
# updating
apt-get -y update
# Installing nginx
apt-get -y install nginx
# Uncomplicated Firewall (UFW) configuration.
# allowing connection on a specific port associated with the Nginx HTTP server
ufw allow 'Nginx HTTP'
# printing it to the file 'index.nginx-debian.html'
# the default location for the default page of the Nginx web
# server on Debian-based systems
echo 'Hello World!' > /var/www/html/index.html

# This block of code defines the Nginx server configuration,
# including listening on port 80,
# specifying the root directory,
# setting the default index files,
# configuring the default server name,
# defining location blocks, and
# adding a redirection rule.
# More explanation in the documentation
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}"

# write the server configuration defined above to the file:
# '/etc/nginx/sites-enabled/default'.
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

# This block checks if the Nginx process is running.
# If not, it starts the Nginx service;
# otherwise, it restarts it.
if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
