#!/usr/bin/env bash
# This script sets up an error page (404)
# Update and install nginx and return "hello worls!"
sudo apt-get update
sudo apt-get install -y nginx

# Check if nginx installation was successful
if ! command -v nginx &> /dev/null; then
    echo "Error: nginx installation failed." >&2
    exit 1
fi

# Create an index.html file
echo 'Hello World!' > index.html

# move the index.html page to the path /var/www/html
sudo mv index.html /var/www/html

# on returning the page contents, it should contain a cutom message  >> "Ceci n'est pas une page"
# move the 404.html to the path /var/www/html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# creating a default site configuration file for nginx
echo "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /var/www/html;
  index index.html;
  location /redirect_me {
    return 301 https://cybersforth.tech
}
  error_page 404 /404.html;
  location = /404.html {
    internal;
}
}" > default
sudo mv -f default /etc/nginx/site-available/default

# restarting the nginx 
sudo service nginx restart
