#!/usr/bin/env bash
# configures the server web-02 like server web-01

# updates the packages
sudo apt-get -y update
# Upgrades the packages
sudo apt-get -y upgrade
# installs nginx
sudo apt-get -y install nginx
# Uncomplicated Firewall (UFW) configuration.
# allowing connection on a specific port associated with the Nginx HTTP server
sudo ufw allow 'Nginx HTTP'
# printing it to the file 'index.nginx-debian.html'
# the default location for the default page of the Nginx web
# server on Debian-based systems
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
