#!/usr/bin/env bash
# Manages the script manage_my_process.
# 	When passed the 'start' argument:
# 		1. It Starts the manage_my_process
#		2. Then it Creates a file containings its PID
# 			in the location /var/run/my_process.pid
# 		3. Then it Displays the string "manage_my_process started"
# 	When the 'stop' argument is passed:
# 		1. The manage_my_process stops
# 		2. it also deletes the file /var/run/my_process.pid
# 		3. and displays the string "manage_my_process stopped"
# 	When passed the 'restart' argument:
# 		1. it Stops the manage_my_process
# 		2. it then deletes the file /var/run/my_process.pid
# 		3. it will now Starts manage_my_process and follows the starts cmd
# 	else: displays
# 		"Usage: manage_my_process {start|stop|restart}"


if [ "${1}" == "start" ]
then
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
	echo "manage_my_process stopped"
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
