#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
sudo apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw disable
sudo ufw enable
# ufw deny all incomming traffic
sudo ufw default deny incoming
# ufw allow the following TCP ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
