#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server
# Requirements:
# 	localhost resolves to 127.0.0.2
# 	facebook.com resolves to 8.8.8.8.
# 	The checker is running on Docker.

cp /etc/hosts ~/hosts.cpy
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.cPY
cp -f ~/hosts.CPY /etc/hosts
