#!/usr/bin/env bash
# A bash script that creates an RSA key pair
# Requiremets:
#	- Name of the created private key must be 'school'
#	- Number of bits in the created key te be created '4096'
#	- Key must be protected by a passphrase 'betty'
ssh-keygen -t rsa -f school -b 4096 -N betty
