#!/usr/bin/env bash
# Bash script that creates an RSA key pair
# -t: specifies the ssh pair type == RSA
# -b: specifies bits value
# -p: specifies the passphrase
# -f: specifies filename 

# defining the variables
key_type='rsa'
key_bit=4096
passphrase='betty'
private_key='school'

ssh-keygen -t "$key_type" -b "$key_bit" -P "$passphrase" -f "$private_key"
